### ISSUE TITLE
Expose API port via a environment variable

### ISSUE THREAD

**Issue by psiemens** [flow-hydraulics/flow-wallet-api#151]
This issue was originally opened here by @m4nuC on July 8, 2021: https://github.com/onflow/wallet-api/issues/9

> Currently, it seems to pick up the default PORT variable which is not ideal in a multi-service environment

From @psiemens:
> @m4nuC Would it help to have a prefix on the environment variable? e.g. FLOW_PORT

From @m4nuC:
> @psiemens yes definitely. Maybe even FLOW_WALLET_PORT or FLOW_WALLET_API_PORT?

**Comment by nanuuki** [comment]
This has been resolved in https://github.com/flow-hydraulics/flow-wallet-api/issues/138 :)
