### ISSUE TITLE
KMS Signer not working for admin account

### ISSUE THREAD

**Issue by psiemens** [flow-hydraulics/flow-wallet-api#154]
This issue was originally opened here by @davidhouseholter-hah on August 20, 2021: https://github.com/onflow/wallet-api/issues/16

> I created a new key in my KMS and converted the PEM to Hex and then created an account on the testnet. When I configure the wallet-api to use this address on the testnet I get the following error:
>
> invalid proposal key: public key 0 on account 0xxxxx does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account 0xxxxx does not have a valid signature: signature is not valid
exit status 1

**Comment by latenssi** [comment]
@davidhouseholter-hah Thank you for bringing this up! This seems pretty straightforward and unless nothing comes up I am confident we will have this implemented tomorrow.

**Comment by latenssi** [comment]
@davidhouseholter-hah we have a PR now and once it is merged, we will do a release of version 0.6.1 containing the changes. Please check the PR for the README file changes for help on how to set it up (it is really quite simple once you have the correct resource identifier).

**Comment by latenssi** [comment]
@davidhouseholter-hah Please refer here for instructions on setup: https://github.com/flow-hydraulics/flow-wallet-api#google-kms-for-admin-account
