### ISSUE TITLE
Docker build failing on Windows machine

### ISSUE THREAD

**Issue by sheerryy** [flow-hydraulics/flow-wallet-api#160]
Hi, I was getting this error on building the wallet docker image on Windows.
```
 > [builder  8/10] RUN ./build.sh:
: not found/build.sh: line 1:
: not found/build.sh: line 3:
#13 0.313 malformed import path "main.go\r": invalid char '\r'
```
It is clear from the error message that it was occurring because of the `\r` EOL character in `build.sh`. I also tried Ubuntu using WSL.

### Solution:
I fixed it using `dos2unix` tool. In short, removed `\r` from the file.

### System Info 
OS Name: Microsoft Windows 10 Pro
Version: 10.0.19043 Build 19043
Docker Desktop: v3.6.0 (67351)

**Comment by latenssi** [comment]
Hi @ShehryarShoukat96 and thank you for brining this up! Did you by any chance modify the files yourself? This seems curios (having the `\r` there) as we mainly use Linux (WSL) for development.

**Comment by ShehryarShoukat96** [comment]
@latenssi  Thanks for getting back on this. I even tried to build docker on a newly cloned repo, but I got the same error. When I removed the `\r` character. My git was detecting the change `CRLF -> LF`. It might be possible that git is adding the character, or it is failing on my machine only. I was able to build the images fine on the previous version.

**Comment by latenssi** [comment]
Hi @sheerryy! I understand it has been a while, but have you resolved this issue?

**Comment by sheerryy** [comment]
@latenssi Yup, It was related to git. Sorry about it. You can mark this as reolved.

**Comment by latenssi** [comment]
Ok, great to hear you solved this! 👍 Closing this issue.
