### ISSUE TITLE
Webhook for Transactions (Jobs) Status

### ISSUE THREAD

**Issue by SiriusDely** [flow-hydraulics/flow-wallet-api#180]
Wondering if there is a plan to add some kind of webhook functionality so that the interested parties can be updated for the status of transactions (jobs) or account creation status, instead of needing to poll the related HTTP API endpoints.

**Comment by nanuuki** [comment]
There's no timeline for this feature yet unfortunately. See related discussions in #155 :)

**Comment by latenssi** [comment]
We are thinking about adding a webhook support for job status updates. This webhook would be configurable via env vars (as everything else) and would receive a POST request on job status updates.

**Comment by SiriusDely** [comment]
@latenssi , glad to hear this, thank you for planning to add this feature.

The requirement you've mentioned above seems to be perfect already.

One thing I'd like to add is to have some kind of retry mechanism with exponential backoff when the webhook was failed to be delivered (not getting back `2xx` http status code as a response).

**Comment by latenssi** [comment]
@SiriusDely Thank you for the feedback!

We will use the existing job scheduling infra for sending the notifications. This means if a webhook fails (error or status code != 200) the scheduler will try again in exactly 1 minute and retry a maximum of 10 times. I understand this is not ideal in a web environment but we don't want to implement a second scheduler just for webhooks. It would be ideal to have the job scheduler doing the exponential backoff some day so all the async jobs benefit from it.

**Comment by SiriusDely** [comment]
sounds great @latenssi !
