### ISSUE TITLE
Is it possible to use AWS KMS instead of Google KMS?

### ISSUE THREAD

**Issue by martin-ccinfo** [flow-hydraulics/flow-wallet-api#183]
As title, could I rewrite the account key stored in the AWS instead and verify the digital signature in the flow transaction? theoretically can do?

**Comment by nanuuki** [comment]
Yes, support for other KMS providers is possible to add :) You can look here for some implementation details in case you're interested in doing it; https://github.com/flow-hydraulics/flow-wallet-api/tree/main/keys

**Comment by latenssi** [comment]
From @tehranifar:
> There is an implementation here you can refer to https://github.com/doublejumptokyo/fcl-kms-authorizer/
