### ISSUE TITLE
Async requests (webhook) not working for a failed transaction

### ISSUE THREAD

**Issue by sheerryy** [flow-hydraulics/flow-wallet-api#220]
Async webhook is working fine when the job is completed successfully. However, When there is an error during the transaction (lets say out storage error), it is not hitting the webhook.

**Comment by latenssi** [comment]
@sheerryy Thank you for bringing this up! I will look into it.

**Comment by latenssi** [comment]
@sheerryy We wanted to limit the webhook calls to only report about *completed* or *failed* jobs. There is a distinction between an *errored* job and a *failed* job: errored jobs will be retried a certain amount of times (10) and if the keep erroring then they will become *failed*. There is also a grace period for errored jobs of 1 minute. So if you have a job that is erroring, it should take around 10-15 minutes for it to become *failed*, at which point you should get a webhook call. Can you verify this (it would be valuable information)?

**Comment by latenssi** [comment]
Ping @sheerryy ☝️

**Comment by sheerryy** [comment]
@latenssi sorry for the late reply, It is working as you mentioned. Thanks. 
On a side note, the error I received in the webhook is
`{
  "jobId": "792b00e2-191a-43a4-b6a4-e3f0f68006de",
  "type": "transaction",
  "state": "FAILED",
  "error": "client: rpc error: code = InvalidArgument desc = transaction with ID 94cb316048b6c8c2b8e4722e1710eaef9192f8bfa2d96fd34b290f8ad14b42c9 has already been submitted",
  "result": "",
  "transactionId": "94cb316048b6c8c2b8e4722e1710eaef9192f8bfa2d96fd34b290f8ad14b42c9",
  "createdAt": "2021-12-01T11:04:37.331492Z",
  "updatedAt": "2021-12-01T11:19:20.1892959Z"
}`
The original error was `Computation resource exceeded`
Maybe this could be an improvement

**Comment by sheerryy** [comment]
What will happen if the mainnet is down? Just curious about it.

**Comment by latenssi** [comment]
> It is working as you mentioned. Thanks.

Great to hear!

>The original error was Computation resource exceeded
Maybe this could be an improvement

This is interesting. Need to dig deeper.

> What will happen if the mainnet is down? Just curious about it.

Most likely the flow client will throw some grpc error and jobs will eventually go in a failed state. But we have not yet planned for this situation and not tested it. That said, we have a PR open which allows putting the service in a maintenance mode, causing the system to halt job and event processing: #222

**Comment by latenssi** [comment]
Closing as this issue has been resolved.
