### ISSUE TITLE
Overhaul logging

### ISSUE THREAD

**Issue by latenssi** [flow-hydraulics/flow-wallet-api#223]
Use a library for logging (logrus for example) and increase logging

**Comment by latenssi** [comment]
To @sheerryy, @uhbif19 and any other member of the community: We are considering of overhauling all logging of the wallet service, meaning the logging output of the service will change drastically. Are you using the log outputs in some automated way? In other words, would this change break your systems?

**Comment by sheerryy** [comment]
@latenssi We are not using log outputs. We are relying on the `state` property of the job.

**Comment by uhbif19** [comment]
@latenssi No, we only use it manually.
