### ISSUE TITLE
Handle chain offline

### ISSUE THREAD

**Issue by latenssi** [flow-hydraulics/flow-wallet-api#224]
To answer the question from the community: 

> What will happen if the mainnet is down?

**Comment by sheerryy** [comment]
@latenssi, I think with the current workflow. When the chain is offline, then all the transactions will fail as you mentioned. However,  it will spawn a worker thread for each transaction. Which will overload the wallet API server, and will be left with no worker. What do you think about it?

**Comment by latenssi** [comment]
Thank you @sheerryy for the comments!

We now have a draft PR (#231) open to asses this issue. As mentioned in the description, this PR will pause all job and event handling for 1 minute if we detect a GRPC error with code `ResourceExhausted`, `Internal` or `Unavailable`. 

But I have to admit I have not experienced a situation where the "network is offline". Therefore I have no experience on what will that actually look like for the wallet service. It is easy to just shutdown the emulator for local testing and that is exactly what this PR currently detects. We will have to setup a separate Flow network and shutdown different parts of it to make sure we detect different error situations  correctly.

In the meantime, if you have any insight on what situations (errors) would make sense for the system to detect, it would be golden @sheerryy 👍

**Comment by sheerryy** [comment]
> Thank you @sheerryy for the comments!
> 
> We now have a draft PR (#231) open to asses this issue. As mentioned in the description, this PR will pause all job and event handling for 1 minute if we detect a GRPC error with code `ResourceExhausted`, `Internal` or `Unavailable`.
> 
> But I have to admit I have not experienced a situation where the "network is offline". Therefore I have no experience on what will that actually look like for the wallet service. It is easy to just shutdown the emulator for local testing and that is exactly what this PR currently detects. We will have to setup a separate Flow network and shutdown different parts of it to make sure we detect different error situations correctly.
> 
> In the meantime, if you have any insight on what situations (errors) would make sense for the system to detect, it would be golden @sheerryy 👍

@latenssi sounds good. I have this error in my logs when the mainnet was down. I hope this will help:
```
{
"createdAt": "2021-12-08T19:27:06.219668Z", 
"error": "client: rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure", 
"jobId": "952628f7-6d76-4bac-a300-5ec368bb7898", 
"result": "", 
"state": "FAILED", 
"transactionId": "", 
"type": "account_create", 
"updatedAt": "2021-12-08T19:41:27.555697565Z"
}
```

**Comment by latenssi** [comment]
Thanks @sheerryy! 

It seems to have the code `Unavailable` which we already check for 👍

**Comment by latenssi** [comment]
@psiemens and @tehranifar Do you think checking for those 3 GRPC error codes (`ResourceExhausted`, `Internal` or `Unavailable`) suffices for detecting if the network is offline?

**Comment by tehranifar** [comment]
You can also add `DeadlineExceeded`.
This might be covered by the above but we also try to cast to `net.Error` and retry if it's a network error:
```
if _, ok := err.(net.Error); ok {
	return true
}
```
