### ISSUE TITLE
Question: error in listener.go

### ISSUE THREAD

**Issue by uhbif19** [flow-hydraulics/flow-wallet-api#229]
I am getting this error in wallet-api logs:

```
[EVENT-POLLER] 2021/12/09 09:16:35 listener.go:87: client: rpc error: code = Internal desc = failed to get events: failed to retrieve block ID for height 10745290: could not retrieve resource: key not found
[EVENT-POLLER] 2021/12/09 09:16:35 listener.go:89: "key not found" error indicates data is not available at this height, please manually set correct starting height
```

But it looks like everything works fine. Is that error normal or I should fix it?

**Comment by nanuuki** [comment]
@uhbif19 please try to adjust the starting height as suggested in the second log entry and see if that resolves the issue. You can do this by setting the `FLOW_WALLET_EVENTS_STARTING_HEIGHT` environment variable. 

Info about past sporks can be found [here](https://docs.onflow.org/node-operation/past-sporks/)

**Comment by uhbif19** [comment]
@nanuuki Are there any documentation on how this works? Am I understanding correctly, that this should be done after every spork? What are implications of this error?

**Comment by uhbif19** [comment]
@nanuuki Added env, still getting error:

`listener.go:87: client: rpc error: code = Internal desc = failed to get events: failed to retrieve block ID for height 50540412: could not retrieve resource: key not found9d885d0cabb6425abfbb1034ef6c199e`

**Comment by latenssi** [comment]
@uhbif19 Everything might seem to work fine but if the event listener is not able to fetch events, the service won't record deposit events from outside the service. This just means the service database won't contain all deposit events for accounts in the service, only those events which originated from the service itself.

Setting the `FLOW_WALLET_EVENTS_STARTING_HEIGHT` should only be necessary if your service has been offline for a while. If you are starting with a fresh database, the service gets the latest height automatically. To my knowledge, sporks should not necessitate setting the env var.

Make sure not to use the same database across different Flow nets (please have a separate database for testnet, mainnet, etc.)

**Comment by latenssi** [comment]
@uhbif19 This just came to my attention (thank you @nanuuki) from the Flow Discord:
> The Flow Testnet has been sporked and the network is back online. Start block height is: 53376277.

So use that number for the env var and you should be fine (**IFF** you are running in `testnet`)

**Comment by latenssi** [comment]
@uhbif19 Did you solve this issue?

**Comment by uhbif19** [comment]
@latenssi Looks like it fixed. But I still not sure how this works. Do I need to do this after each spork?

**Comment by latenssi** [comment]
@uhbif19 We will document this in more detail. Closing this now!
