### ISSUE TITLE
Job accepted status is not used

### ISSUE THREAD

**Issue by seita-uc** [flow-hydraulics/flow-wallet-api#241]
Currently it seems job is never turned to `Accepted` status.

**Comment by latenssi** [comment]
@seita-uc Thanks for noticing this! I think we could just drop that state from the codebase.

**Comment by seita-uc** [comment]
@latenssi I think it's better to have`Accepted` state to distinguish whether the job is just created or being processed.
I will make a PR to update job state to `Accepted` inside the [`accept()` function](https://github.com/flow-hydraulics/flow-wallet-api/blob/556afa23ebd7a79a540cda8efad19914e6d656f3/jobs/workerpool.go#L197-L211) if that sounds right to you.

**Comment by latenssi** [comment]
My only concern is adding functionality that is not actually used, but if you see this adds value to you (a user of the project) then it is enough of a reason for me to add this. 

@seita-uc Ty, great if you could make a PR for it!
