### ISSUE TITLE
Error while sending transactions

### ISSUE THREAD

**Issue by uhbif19** [flow-hydraulics/flow-wallet-api#250]
I am getting 400 on transaction sending for one account:

```error while getting new transaction: error while building transaction: error while getting user authorizer: cipher: message authentication ```

**Comment by nanuuki** [comment]
@uhbif19, this looks like an error you might get if the encryption key is changed. Have you changed the value for `FLOW_WALLET_ENCRYPTION_KEY`?

**Comment by uhbif19** [comment]
@nanuuki No. And other users worked okay.

**Comment by nanuuki** [comment]
@uhbif19 ok, can you provide any additional details about the account & configuration? Are you using local or KMS keys for example?
