### ISSUE TITLE
Add a standalone docker-compose file

### ISSUE THREAD

**Issue by wphan** [flow-hydraulics/flow-wallet-api#266]
I tried following the README.md instructions to run this stack locally, but the `api` service exits without any logs or hint of what went wrong (both `make dev` and `docker-compose -f docker-compose.dev.yml up` fails like this).

After some digging, I found the `docker-compose.*.yml` files target the `dependencies` stage for the `api` service (https://github.com/flow-hydraulics/flow-wallet-api/blob/main/docker-compose.dev.yml#L48).  Changing the target to the final stage `dist` will start up the stack as expected. 

Is there any reason for the compose files to target the `dependencies` stage? If not I can open a PR with this fix.

**Comment by latenssi** [comment]
Hi @wphan thanks for bringing this up! You are correct.

The reason those are targeting the _dependencies_ stage is we are using the _dev_ variant only for development purposes and the _test-suite_ variant for testing. There is currently no variant for running the wallet as a local service.

We should add a docker-compose variant for a complete local service setup. I am renaming this issue to reflect this requirement.

Sorry for the inconvience! 🙏
