### ISSUE TITLE
Secure Cadence Upgrade Plan?

### ISSUE THREAD

**Issue by elizabethengelman** [flow-hydraulics/flow-wallet-api#295]
Hello folks, curious if there are plans to update this project to use the up-to-date Secure Cadence dependencies ([emulator](https://github.com/onflow/flow-emulator/releases/tag/v0.32.0), flow-go-sdk, cadence, etc)?

**Comment by elizabethengelman** [comment]
For some more context about our specific issue. We are using the `FLOW_WALLET_SCRIPT_PATH_CREATE_ACCOUNT` env var to pass a custom script when creating new accounts. I recently upgraded our custom account script to expect the public keys to be a `Crypto.KeyListEntry` collection, to match how it's being done in the more recent [flow-go-sdk versions](https://github.com/onflow/flow-go-sdk/blob/de1578d8e5105f23638d5bde7cf0911ab9252a5f/templates/accounts.go#L132).

```
transaction(publicKeys: [Crypto.KeyListEntry], contracts: {String: String}) {...}
```

However, I think that the flow-wallet-api still uses an older version of the flow-go-sdk (v.0.24.0) which does not convert the key arguments to a `Crypto.KeyListEntry` collection when [creating the CreateAccount transaction](https://github.com/onflow/flow-go-sdk/blob/v0.24.0/templates/accounts.go#L75), so we're seeing the following error.

I realize this isn't strictly a secure cadence change, but an upgrade to the flow-go-sdk would help, so we were just curious about the plans to upgrade so we can get that done on our own fork if need be. :)

```
emulator_1  | time="2022-06-08T15:56:40Z" level=warning msg="\x1b[1;31mERR\x1b[0m \x1b[2m[bc6a63]\x1b[0m [Error Code: 1101] cadence runtime error Execution failed:\nerror: invalid argument at index 0: value does not conform to expected type `[Crypto.KeyListEntry]`\n--> bc6a63fc528a705008aa5a16894a4306b28203f071af1007a640b6018307b6a5\n"
```

**Comment by nvdtf** [comment]
Thanks for the PR https://github.com/flow-hydraulics/flow-wallet-api/pull/296
