### ISSUE TITLE
Operation recovery support across endpoints

### ISSUE THREAD

**Issue by nanuuki** [flow-hydraulics/flow-wallet-api#78]
Operation recovery support across endpoints. Running a transaction and waiting for it to seal is time consuming, and service restarts in a container environment (e.g. Kubernetes cluster) are common. If a transaction is sent to the network and the container is restarted while the status is being polled, the operation won’t resume after restart. To fix this, it’s best to insert into the database with pending status when a request is received, and check/resume non-terminal records on service startup.

**Comment by latenssi** [comment]
fixed in #196
