### ISSUE TITLE
Always assume 1 signer

### ISSUE THREAD

**Issue by nanuuki** [flow-hydraulics/flow-wallet-api#79]
The code string checks `: AuthAccount` to decide whether a signature is needed. We think it’s best to always assume 1 signature is needed and specify it in the docs.

**Comment by latenssi** [comment]
This is a bit problematic as the service can receive a raw transaction request which does not need signers at all (or multiple signers).

That being said, if we only allow transactions that require exactly 1 signature (authorizer), it would simplify the code and responsibilities of the service.
