### ISSUE TITLE
Proposer key sequence at higher loads

### ISSUE THREAD

**Issue by nanuuki** [flow-hydraulics/flow-wallet-api#86]
The proposer key sequence number is fetched from Flow with `GetAccount`. This has the side-effect of failing transactions during high load due to incorrect sequence numbers. You can use the master account’s key as proposer for other accounts if locking/throttling is planned for that account. It should be noted in the docs that handling higher load is in the works.

**Comment by latenssi** [comment]
@tehranifar I am not entirely sure I understand the wanted outcome of this issue but didn't you implement something in these lines already?

**Comment by tehranifar** [comment]
Yeah we can close this, the multi-proposal key feature handles this.
