### ISSUE TITLE
Variable naming conventions

### ISSUE THREAD

**Issue by nanuuki** [flow-hydraulics/flow-wallet-api#99]
Avoid using single letter variable names like `a`, `aa`, `b` in the code.

**Comment by tuommaki** [comment]
This task is slightly controversial. So far as I've been working with the code base, I personally think that variable naming has been fine. It does have single letter variable names, but mostly in short scope use cases.

In Go programming language, it's very common to use short variable names when the scope is short and code is trivial in the sense that the longer, possibly more descriptive variable name wouldn't provide any added value for readability.

I took a look through couple Go repositories' `CONTRIBUTING.md` ([flow-go](https://github.com/onflow/flow-go) and [flow-go-sdk](https://github.com/onflow/flow-go-sdk)) and both of them refer to [Effective Go](https://golang.org/doc/effective_go) and [Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments) for style guides.

The Go Code Review Comments specifically have [a section on variable names](https://github.com/golang/go/wiki/CodeReviewComments#variable-names) which states the following:

> Variable names in Go should be short rather than long. This is especially true for local variables with limited scope. Prefer c to lineCount. Prefer i to sliceIndex.
>
> The basic rule: the further from its declaration that a name is used, the more descriptive the name must be. For a method receiver, one or two letters is sufficient. Common variables such as loop indices and readers can be a single letter (i, r). More unusual things and global variables need more descriptive names.

Therefore, as there are no specific examples or pointers of improper short variable name usage, I won't take further actions here.
